### ISSUE TITLE
link-type that is self-referencing from same entry-type to same entry-type yields error

### ISSUE THREAD

**Issue by jmday** [holochain/scaffolding#75] opened 2023-02-26 00:41 UTC
link-entry scaffold tool creates code that doesn’t compile
   Compiling name_graph v0.0.1 (/Users/jmday/dev/holo/hello_link/dnas/name_graph/zomes/coordinator/name_graph)
error[E0124]: field `name_entry_hash` is already declared
 --> dnas/name_graph/zomes/coordinator/name_graph/src/name_entry_to_name_entries.rs:6:5
  |
5 |     pub name_entry_hash: ActionHash,
  |     ------------------------------- `name_entry_hash` first declared here
6 |     pub name_entry_hash: ActionHash,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ field already declared

**Comment by c12i** [comment] 2024-01-09 12:41
Hello @jmday could you provide the commands I need to run step by step so that I can reproduce this?

**Comment by c12i** [comment] 2024-11-21 14:18
Closing this since it's not reproducible, can be re-opened if it emerges again

**Closed by c12i** 2024-11-21 14:18 UTC
Labels: question
