### ISSUE TITLE
Package ‘webkitgtk-2.38.2+abi=4.0’ in /nix/store/73w8ml8wf35agm65ihdanz42yj7n8cz3-source/pkgs/development/libraries/webkitgtk/default.nix:241 is marked as broken, refusing to evaluate

### ISSUE THREAD

**Issue by bierlingm** [holochain/scaffolding#58] opened 2023-01-17 18:12 UTC
I installed Nix on my MacBook Pro with an M1 chip.

I ran the following command while following the instructions on the Holochain Developer documentation:

`nix-shell https://holochain.love --run "hc scaffold example forum"`

It did a bunch of stuff and then ended up erroring out in the following way:

<img width="682" alt="Screenshot 2023-01-17 at 7 08 15 PM" src="https://user-images.githubusercontent.com/9335771/212978297-474d535e-6789-4696-b2e2-11ee56982ba8.png">

Do I follow its instructions for allowing broken packages or is that something that needs to be addressed in the scaffolding itself?

**Comment by c12i** [comment] 2024-10-22 16:57
Closing since this is not reproducible, and quite outdated. Would recommend trying to follow the most recent instructions for scaffolding a hApp in the [dev portal ](https://developer.holochain.org/get-started/)

**Closed by c12i** 2024-10-22 16:57 UTC
