### ISSUE TITLE
When using a template, after scaffolding web app, it prompts to create entry

### ISSUE THREAD

**Issue by artbrock** [holochain/scaffolding#127] opened 2023-09-25 06:57 UTC
I believe this only happens in the context of referencing a template when generating the web-app.

After scaffolding web-app, it prompts to create an entry as the next action.

This jumps too far ahead in sequence. Creation of DNA and a Zome are required before creating an entry.

**Comment by c12i** [comment] 2024-10-15 11:04
Closing this since it could not be reproduced. Perhaps the custom template was at fault

**Closed by c12i** 2024-10-15 11:04 UTC
